config/routes.rb
MusicApp::Application.routes.draw do
  root :to => "bands#index"
  get '/users/activate' => 'users#activate'
  resources :users

  resource :session, :only => [:new, :create, :destroy]
  resources :bands do 
    resources :albums, :only => [:index, :new, :create]
  end
  resources :albums, :only => [:show, :edit, :update, :destroy] do 
    resources :tracks, :only => [:index, :new, :create]
  end
  resources :tracks, :only => [:show, :edit, :update, :destroy] do 
    resources :notes, :only => [:new, :create]
  end
  resources :notes, :only => [:show, :edit, :update, :destroy]
end

app/models/track.rb
class Track < ActiveRecord::Base
  self.inheritance_column = nil  
  attr_accessible :name, :type, :lyrics, :album_id
  validates :name, :type, :lyrics, :album_id, :presence => true
  
  belongs_to :album,
             :primary_key => :id,
             :foreign_key => :album_id,
             :class_name => 'Album'
             
  has_many :notes, 
           :primary_key => :id, 
           :foreign_key => :track_id, 
           :class_name => 'Note',
           :dependent => :destroy
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  
  def index
    @tracks = Track.all
    render :index
  end
  
  def show
    @track = Track.find(params[:id])
    render :show
  end
  
  def new
    @album = Album.find(params[:album_id])
    render :new
  end
  
  def create
    @track = Track.new(params[:track])
    @track.lyrics = ugly_lyrics(@track.lyrics)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages.first
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def destroy
    @track = Track.find(params[:id])
    @track.delete
    redirect_to album_tracks_url(@track.album)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
  
  def ugly_lyrics(lyrics)
    modified = lyrics.split("\n")
    modified.map! { |each_line| "\u266b" + each_line }
    modified.join("\n")
  end
end

app/views/tracks/index.html.erb
<h1>Tracks</h1>
<% @tracks.each do |track| %>
<%= track.id %>
	<%= link_to "#{track.name}", track_url(track.id) %><br>
<% end %>

app/views/tracks/new.html.erb
<h1>Add a Track!</h1>
<%= flash.now[:errors] %>

<form action="<%= album_tracks_url(@album) %>" method="post" accept-charset="utf-8">
	
<input type="hidden"
			 name="authenticity_token"
			 value="<%= form_authenticity_token %>">
			 
<label for="name">Name</label><input type="text" name="track[name]" value="" id="name">

<input type="hidden" name="track[album_id]" value="<%= @album.id %>" id="track[album_id]">

<select name="track[album_id]" id="track[album_id]" size="1">
	<% Album.all.each do |album| %>
		<option value="<%= album.id %>"><%= album.title %></option>
	<% end %>
</select>

<label for="regular">Regular</label>
<input type="radio" name="track[type]" value="regular" id="regular">

<label for="bonus">Bonus</label>
<input type="radio" name="track[type]" value="bonus" id="bonus"><br>

<label for="lyrics">Lyrics</label><br><textarea rows="10" cols="30" name="track[lyrics]" id="lyrics"></textarea>

			 
			 
	<p><input type="submit" value="Continue &rarr;"></p>
</form>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
Album: <%= link_to "#{@track.album.title}", album_url(@track.album.id) %><br>

Type: <%= @track.type %><br>
<h2>Lyrics</h2><br>
<pre>
<%= @track.lyrics %>
</pre>

<h3>Notes(<%= @track.notes.count %>)</h3>
<% unless @track.notes.empty? %>
	<% @track.notes.each do |note| %>
	Note <%= note.id %>:
		<%= note.body %>
		<%= button_to "Delete Note", note_url(note), :method => :delete %>
	<% end %>
<% end %>

<%= flash.now[:errors] %>

<form action="<%= track_notes_url(@track.id) %>" method="post" accept-charset="utf-8">
<input type="hidden"
			 name="authenticity_token"
			 value="<%= form_authenticity_token %>">
		
<label for="notes">Add New Note</label><br>
<textarea rows="10" cols="30" name="note[body]" id="notes"></textarea>

	<p><input type="submit" value="Continue &rarr;"></p>
</form>


Delete:<%= button_to "Delete Track", track_url(@track), :method => :delete %>