config/routes.rb
MusicApp::Application.routes.draw do
  root :to => "bands#index"
  get '/users/activate' => 'users#activate'
  resources :users

  resource :session, :only => [:new, :create, :destroy]
  resources :bands do 
    resources :albums, :only => [:index, :new, :create]
  end
  resources :albums, :only => [:show, :edit, :update, :destroy] do 
    resources :tracks, :only => [:index, :new, :create]
  end
  resources :tracks, :only => [:show, :edit, :update, :destroy] do 
    resources :notes, :only => [:new, :create]
  end
  resources :notes, :only => [:show, :edit, :update, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base
  self.inheritance_column = nil
  attr_accessible :title, :type, :band_id
  validates :title, :type, :band_id, :presence => true
  
  belongs_to :band,
             :primary_key => :id,
             :foreign_key => :band_id,
             :class_name => 'Band'
             
  has_many :tracks, 
           :primary_key => :id,
           :foreign_key => :album_id,
           :class_name => 'Track',
           :dependent => :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  def index
    render :index
  end
  
  def show
    @album = Album.find(params[:id])
    render :show
  end
  
  def new
    @album = Album.new
    render :new
  end
  
  def create
    @album = Album.new(params[:album])
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages.first
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def destroy
    @album = Album.find(params[:id])
    @album.delete
    redirect_to band_albums_url(@album.band)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/new.html.erb
<h1>Add an Album!</h1>
<%= flash.now[:errors] %>

<form action="<%= band_albums_url %>" method="post" accept-charset="utf-8">
	
<input type="hidden"
			 name="authenticity_token"
			 value="<%= form_authenticity_token %>">
			 
<label for="title">Title</label><input type="text" name="album[title]" value="" id="title">

<select name="album[band_id]" id="album[band_id]" size="1">
	<% Band.all.each do |band| %>
	<option value="<%= band.id %>"><%= band.name %></option>
	<% end %>
</select><br>

<label for="studio">Studio</label>
<input type="radio" name="album[type]" value="studio" id="studio">

<label for="live">Live</label>
<input type="radio" name="album[type]" value="live" id="live">
			 
	<p><input type="submit" value="Continue &rarr;"></p>
</form>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
Band: <%= link_to "#{@album.band.name}", band_url(@album.band.id)%><br>

Tracks: 
<% unless @album.tracks.empty? %>
	<% @album.tracks.each do |track| %>
		<%= link_to "#{track.name}", track_url(track) %><br>
	<% end %>
<% end %>

Delete:<%= button_to "Delete Album", album_url(@album), :method => :delete %>