config/routes.rb
MusicApp::Application.routes.draw do
  root :to => "bands#index"
  get '/users/activate' => 'users#activate'
  resources :users

  resource :session, :only => [:new, :create, :destroy]
  resources :bands do 
    resources :albums, :only => [:index, :new, :create]
  end
  resources :albums, :only => [:show, :edit, :update, :destroy] do 
    resources :tracks, :only => [:index, :new, :create]
  end
  resources :tracks, :only => [:show, :edit, :update, :destroy] do 
    resources :notes, :only => [:new, :create]
  end
  resources :notes, :only => [:show, :edit, :update, :destroy]
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true
             
  has_many :albums, 
           :primary_key => :id,
           :foreign_key => :band_id,
           :class_name => 'Album', 
           :dependent => :destroy
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  
  def index
    @bands = Band.all
    render :index
  end
  
  def show
    @band = Band.find(params[:id])
    render :show
  end
  
  def new
    render :new
  end
  
  def create
    @band = Band.new(params[:band])
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages.first
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def destroy
    
  end  
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/index.html.erb
<h1>Welcome to Music App!!</h1>
<h2>List of all bands in DB</h2>
<% @bands.each do |band| %>
	<%= link_to band.name, band_url(band) %>
<% end %>

app/views/bands/new.html.erb
<h1>Add a Band!!</h1>
<%= flash.now[:errors] %>

<form action="<%= bands_url %>" method="post" accept-charset="utf-8">
	
<input type="hidden"
			 name="authenticity_token"
			 value="<%= form_authenticity_token %>">
			 
			 <label for="band">Band</label><input type="text" name="band[name]" value="" id="band">
			 
	<p><input type="submit" value="Continue &rarr;"></p>
</form>

app/views/bands/show.html.erb
<h1><%= @band.name.capitalize %></h1>
<h2>Albums</h2>

<% unless @band.albums.empty? %>
	<% @band.albums.each do |album| %>
		<%= link_to "#{album.title}", album_tracks_url(album.id) %>
	<% end %>
<% end %>

Delete:<%= button_to "Delete Band", band_url(@band), :method => :delete %>